name: cangulo-actions/semver test
on:
  push: 
    branches:
      - main

jobs:
  test-semver:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for pushing to main, it is a protected branch

      - name: Release new version
        uses: cangulo-actions/semver@update-docs